[build]
  command = "npm run every-install && npm run deploy-linux"
  publish = "server/dist"   # Publish directory for the client-side files
  functions = "server/dist/netlify/functions"  # Path to the serverless functions


  
[build.environment]
  CI = ""

[dev]
  command = "npm run server-dev"


[functions]
  directory = "server/dist/netlify/functions"

[[redirects]]
  force = true
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200