[build]
  command = "npm run every-install && npm run deploy-linux"
  publish = "server/dist"   # Publish directory for the client-side files

[build.environment]
  CI = ""


[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"